# Generated by Django 5.2.1 on 2025-05-19 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricoPesquisa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Data e hora da pesquisa"
                    ),
                ),
                (
                    "termo_pesquisado",
                    models.TextField(
                        help_text="Termo ou descrição da pesquisa realizada"
                    ),
                ),
                (
                    "resultado_resumido",
                    models.TextField(
                        blank=True,
                        help_text="Resumo do resultado da pesquisa",
                        null=True,
                    ),
                ),
                (
                    "vara",
                    models.CharField(
                        blank=True,
                        help_text="Vara relacionada à pesquisa, para filtragem",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        help_text="Usuário que realizou a pesquisa",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Pesquisa",
                "verbose_name_plural": "Históricos de Pesquisas",
                "ordering": ["-timestamp"],
            },
        ),
    ]
